name: Deploy to Live Channel

on:
  push:
    branches:
      - master
name: Firebase hosting
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install firebase tools
      run: |
        firebase use <FIREBASE PROJECT ID> --token ${{ secrets.FIREBASE_TOKEN }}
    - name: Build website
    - name: Deploy to staging site
      if: github.ref == 'refs/heads/main'
      run: firebase deploy --only hosting:practice --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"
      run: firebase deploy --only hosting:admin --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"

    - name: Archive build Artifact
      uses: actions/upload-artifact@master
      with:
        path: build
# name: Deploy to Firebase Hosting on merge
# 'on':
#   push:
#     branches:
#       - main
# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: npm ci && npm run build
#       - uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DARON_B15B1 }}'
#           channelId: live
#           projectId: daron-b15b1
#         env:
#           FIREBASE_CLI_PREVIEWS: hostingchannels
